language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest # or py.test for Python versions 3.5 and below