language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coveralls
before_script: 
  - "sudo add-apt-repository ppa:mc3man/trusty-media -y"
  - "sudo apt-get update"
  - "sudo apt-get install ffmpeg"
script:
  - pytest
  - coverage run --source=converto setup.py test
  - coveralls